name: conda recipe

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule but only for the default branch (which is master)
  schedule:
   - cron: '0 7 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_recipe"
  check_recipe:
    name: test bioconda recipes on ${{ matrix.os }} with python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest','macos-latest']
        python-version: ['3.8','3.9','3.10']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setting up miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda,defaults
      - name: Set up test environment
        shell: bash -l {0}
        run: |
            conda install -y ppanggolin
      - name: check installation
        shell: bash -l {0}
        run: |
            python --version
            ppanggolin --version
      - name: all workflow run
        shell: bash -l {0}
        run: |
          cd testingDataset/
          ppanggolin all --cpu 1 --anno genomes.gbff.list -o pango
          ppanggolin info -p pango/pangenome.h5 --content --parameters --status
